### ISSUE TITLE
Failed to resolve:'com.afollestad:material-dialogs:0.7.8.0

### ISSUE THREAD

**Issue by viveksonihmr** [spark/photon-tinker-android#1]
When I am run this ticker app,then during building gradle,an error is occur Shows as - Failed to resolve:'com.afollestad:material-dialogs:0.7.8.0

<img width="674" alt="capture" src="https://cloud.githubusercontent.com/assets/10378401/10843625/697c2c54-7f3d-11e5-961c-c2f5142f1228.PNG">

Please help me,to solve this.thanks in advance!

**Comment by prashantgosai26** [comment]
@viveksonihmr are you get solution of above problem...?
if you get it please help me to solve it
i'm getting same problem

**Comment by jensck** [comment]
The latest version of the app shouldn't have this problem.  Try pulling the latest from git and cleaning your build.

This should resolve the issue, but if it doesn't, feel free to re-open this!

**Comment by viveksonihmr** [comment]
Thanks jens! This problem have been solved,Now its working fine.
:)

On Tue, Nov 17, 2015 at 3:39 AM, Jens Knutson <notifications@github.com>
wrote:

> The latest version of the app shouldn't have this problem. Try pulling the
> latest from git and cleaning your build.
>
> This should resolve the issue, but if it doesn't, feel free to re-open
> this!
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/spark/photon-tinker-android/issues/1#issuecomment-157130898>
> .
>



-- 
*Er.Vivek Soni*
Integrated Circuit Interface Lab
College of Electronics and Radio Engineering
*Kyunghee University(KHU),Suwon,South Korea*
