### ISSUE TITLE
"I forgot my password" from app not working

### ISSUE THREAD

**Issue by bloukingfisher** [spark/photon-tinker-android#10]
I've verified that it works on an iPhone but on Android (Samsung Galaxy S6 Android version 6.0.1) on the Particle app if you click the link "I forgot my password" it seems to open a mobile web page with the message "Looks like you got lost". The menu item from this page doesn't offer a link to retrieve a password and requires a user to know and go to the website to reset a password.

I suspect it is an outdated URL/resource that is not auto directing/updated.

**Comment by jenesaisdiq** [comment]
Seconded @idokleinman and thirded by Chris.
