### ISSUE TITLE
Failed to resolve:'com.afollestad:material-dialogs:0.7.9.1

### ISSUE THREAD

**Issue by themakerbro** [spark/photon-tinker-android#2]
Similar to issue #1.  Latest version of the app fails to build.

![screen shot 2015-12-27 at 2 59 58 am](https://cloud.githubusercontent.com/assets/7302561/12009936/71623056-ac44-11e5-846e-e40704a114eb.png)

**Comment by swetabh007** [comment]
The latest version of the app shouldn't have this problem. Try pulling the latest from git and cleaning your build.

This should solve your problem.

**Comment by vibhorsd** [comment]
The problem is still there, I don't see any commit pushed to fix this.

**Comment by jensck** [comment]
@vibhorsd I've applied 90% of the complete fix on master, and a temporary fix for the remaining 10% just to get it compiling.  Pull from master and clean, and it will build.
