### ISSUE TITLE
Don't prevent installs on devices without a rear camera

### ISSUE THREAD

**Issue by jensck** [spark/photon-tinker-android#4]
Looks like the Electron setup barcode scanning support is preventing installation on devices with no rear camera.

Look into how we can support these devices and provide a bit of feedback when they try to launch the barcode scanner.

**Comment by harrisonhjones** [comment]
Let them type it in manually? That's what Android Pay does. What does the Barcode scanner do if you do launch it w/o a proper camera?

**Comment by idokleinman** [comment]
Out of curiosity - which devices today have no rear camera?

**Comment by harrisonhjones** [comment]
Well, the original issue came from a guy with a Nexus 7 running Android 5.1.1 but I'm sure that has a rear camera

**Comment by jensck** [comment]
The more popular, more recent 2013 Nexus 7 had one, but the OG 2012 Nexus 7 did not: https://en.wikipedia.org/wiki/Nexus_7_(2012)#Critical

It's fairly rare for devices not to have a rear camera.  These days it seems more common to omit the front  camera instead when OEMs are looking to cut costs.
