### ISSUE TITLE
Missing drawable

### ISSUE THREAD

**Issue by JamesWhitfield** [spark/photon-tinker-android#5]
missing drawable/abc_ic_menu_moreoverflow_mtrl_alpha

which is used in row_device_list.xml

**Comment by jensck** [comment]
Was this issue showing up specifically with the 23.2 version of the support library?

If so, can you reproduce it with 23.1.x?

**Comment by JamesWhitfield** [comment]
changing the gradle files to build from 23.1.1 seems to have no effect on the generated aars. the project still generates 23.2.0 libraries. Are you including these from another source?

**Comment by JamesWhitfield** [comment]
23.2.0 was being built from the other dependencies. adding 

compile ('com.android.support:appcompat-v7:23.1.0'){
        force = true
    }

solved the issue.
